### ISSUE TITLE
Extend module to support modern versions of ruby

### ISSUE THREAD

**Issue by igalic** [camptocamp/puppet-augeas#39]
We use the brightbox PPA to pull in Ruby 1.9.x on Ubuntu precise (old LTS) and will use it to pull in Ruby 2.1.x into Ubuntu trusty (new LTS).

We'll need to extend the support here. (As there is no direct support from Ubuntu, and it doesn't exist in [@raphink's ppa yet](https://launchpad.net/~raphink/+archive/augeas/) either, for now we'd have to install ruby-augeas from gem.

That in turn requires libaugeas-dev and pkg-config. The latter of which is problematic, since it could be managed in other modules.

**Comment by antaflos** [comment]
@raphink Just stumbled across this again. I am evaluating how painful or easy it is to upgrade to at least Ruby 2.1 on Ubuntu 12.04 and 14.04 (in both cases from 1.9.3). We use [Brightbox's Ruby-NG PPA](https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng) which is probably the only worthwhile source of packages for modern Ruby on older Ubuntu versions. Seems they provide Ruby 1.8.7, 1.9.3, 2.0, 2.1 and 2.2 for all Ubuntu versions.

Your PPA only provides libaugeas-ruby1.9.1 and libaugeas-ruby1.8 for Ubuntu 12.04 and 14.04 so naturally Augeas will not work after switching to Ruby 2.1.

What can we do here?

I think making your PPA depend on Brightbox's for libaugeas-ruby2.0, libaugeas-ruby2.1 and libaugeas-ruby2.2 is feasible since those who need to run modern Ruby on older Ubuntu versions must use the Brightbox PPAs anyway (or package their own Ruby in which case they can probably package their own Augeas as well).

**Comment by raphink** [comment]
I'm wondering if this is really worth the effort, considering Puppet 4 now comes in AIO package which provide Ruby itself. People who care to use recent software will most lilkely use that and not required Ruby backports.

**Comment by igalic** [comment]
same, except puppet 4 seems to be… still quite painful to use :(

**Comment by raphink** [comment]
It's a necessary pain, it will make you better on the long run ;-)

**Comment by igalic** [comment]
… but… will it make *puppet* better?
